language: node_js
node_js:
- '4.2'
deploy:
  email: benauf@gmail.com
  provider: npm
  api_key:
    secure: Z9usvBnxPT3RMdnX0nDFc2mekI5xY/Vl9tTKo13BFgJVkXCTh3pzazCPpjkwSp0HjPhAnSOLkPOU+B16/ri5srZSlPklTgCqh4ZJBLO5kVaN9434GSqlHk8Xza/2k71a6o8w5XIwcestX6jF6jBvtn+SEEN0/rDziKyC4I8kAtrvMuLfmtQah1zHUhaMbAOep1AVa/Wk/Ov3+QvgkpPnKu+uvPHYJ9ruIF7hfTx1REp+bWcWFlx+F+xkAc1IT1I0ymA0rpRwuCp9ybgGyEdpuNnEWiqLuSgZOEj6KG20ASfDuDfwjoWNR+Gxp88stCeDtvq64kmYsGT4ri551YDRrHtuQZdVISmXBzjdFFruxu8dUtuKPXFWNX+ecl8cijU/tiuC6cysVRDlCAQDISFGJZbqOsFEA9MbCy5iP4ALFpJxOAMPvFv3Dem1K4zZgDdd03iUp/+xeQDBKYmOaf89V5gVnafkI9PeQ3TNrtS0VZrh9pH7pQwByl0fal+LMGG65FJuaG3lSh1jPJeZJnJvPWZn06jVTqYjsDxnpr0k1f2VCpv7e/lNADv+dAv8S1sFPTHGSQgKl+iTZ48ZdEoK4/3hOsLngaNlqmdzhI+geU2DP8MpMzJeukdSVluguovuVERGceZ2DJSGl/5GwqHmb0coVbUNmfyR1d1YzqzqeMs=
